### ISSUE TITLE
bug: cortex.cpp Installer IPersistFile::Save failed; code 0x80070005. Access is Denied

### ISSUE THREAD

**Issue by dan-menlo** [janhq/cortex.cpp#1216]
### Cortex version

0.5.0-55

### Describe the Bug

- Windows Installer for cortex.cpp has error, but continues to install
- UX for downloading llama.cpp dependency needs some work

### Screenshots / Logs

**Error that showed up:**
![image](https://github.com/user-attachments/assets/cb857a2f-dee6-4a91-a59a-805f89960a2c)

After that, cortex.cpp indicated that Cortex was added to path:

**CUDA download in progress**
- As a user, it was confusing as no progress was shown
![image](https://github.com/user-attachments/assets/dc6075fe-d07a-478c-9b36-9855d20be5a3)

### What is your OS?

- [ ] MacOS
- [X] Windows
- [ ] Linux

### What engine are you running?

- [X] cortex.llamacpp (default)
- [ ] cortex.tensorrt-llm (Nvidia GPUs)
- [ ] cortex.onnx (NPUs, DirectML)

**Comment by hiento09** [comment]
Thanks, @dan-homebrew. Since Cortex is not a GUI/Desktop application, I will disable the options `Create a desktop icon` and `Create a Quick Launch icon.` I believe this will fix the error.

Regarding the download percentage for the llamacpp engine, the current source code does not support showing the download progress.I'll look for a way to add it to the installer dialog instead of showing the console log.

**Comment by hiento09** [comment]
@dan-homebrew, can you check if [this installer](https://github.com/janhq/cortex.cpp/actions/runs/10870302683/artifacts/1934525482) fixes your issue?
