### ISSUE TITLE
bug: exit() does not exit chat

### ISSUE THREAD

**Issue by dan-menlo** [janhq/cortex.cpp#1424]
### Cortex version

154

### Describe the Bug

When I typed exit(), the chat did not exit. Only typing exit() a second time caused it to exit

### Screenshots / Logs

![Image](https://github.com/user-attachments/assets/16004b99-b1e3-4290-affb-940f384c1782)

### What is your OS?

- [x] MacOS
- [ ] Windows
- [ ] Linux

### What engine are you running?

- [x] cortex.llamacpp (default)
- [ ] cortex.tensorrt-llm (Nvidia GPUs)
- [ ] cortex.onnx (NPUs, DirectML)

**Comment by namchuai** [comment]
I can't reproduce this issue on latest version `1.0.0-169`
Tried to go back to `154` but I can't run because the engine name is now different (llama-cpp to llama.cpp)

<img width="748" alt="Screenshot 2024-10-15 at 19 55 13" src="https://github.com/user-attachments/assets/0c2a4d35-3e40-41f1-bfe4-5a87a57f9d67">

@dan-homebrew  @gabrielle-ong , could you please upgrade cortex and try to reproduce this issue?

**Comment by gabrielle-ong** [comment]
Confirmed resolved, not getting this issue anymore v170 onwards
