### ISSUE TITLE
bug: Cant run `cortex` and `cortex-nightly` at the same time

### ISSUE THREAD

**Issue by gabrielle-ong** [janhq/cortex.cpp#1478]
### Cortex version

v1.0.0 Stable and Nightly-168

### Describe the Bug

Mac M1 Sillicon, tried with both mac universal network and local installers

Overall: Installed cortex then cortex-nightly -> can only run cortex-nightly

Installation:
1. Download both cortex and cortex-nightly installers
2. Install one of them eg cortex, `cortex` successfully runs
4. Install cortex-nightly, `cortex-nightly` successfully runs
5. try `cortex` again, no command found

In addition, I notice that in Mac /usr/local/bin (where uninstall scripts are),
Installed cortex then cortex-nightly ->
`cortex` and `cortex-uninstall.sh` is removed, replaced with `cortex-nightly` and `cortex-nightly-uninstall.sh`
I did not delete any files, just installed `cortex` then `cortex-nightly`
I would have expected to see both `cortex` AND `cortex-nightly`
<img width="831" alt="image" src="https://github.com/user-attachments/assets/e77530f3-e095-4a0c-a701-d487e1db0629">

### What is your OS?

- [X] MacOS
- [ ] Windows
- [ ] Linux

### What engine are you running?

- [X] cortex.llamacpp (default)
- [ ] cortex.tensorrt-llm (Nvidia GPUs)
- [ ] cortex.onnx (NPUs, DirectML)

**Comment by gabrielle-ong** [comment]
Hi @hiento09 I upgraded to cortex-nightly-169, then redownloaded cortex-stable but still have the issue
Does cortex-stable need to be updated too?
<img width="723" alt="image" src="https://github.com/user-attachments/assets/653b4c8f-d9bd-4b2d-8737-01b39daa331b">

**Comment by hiento09** [comment]
Hi @gabrielle-ong , you will need to uninstall the old nightly versions and install the new version of Cortex Nightly, but you can keep the stable version as it is. 

I want to explain the reason why we encountered this issue. When I created the package file, I mistakenly used the same name for all three versions—stable, beta, and nightly—as 'stable,' which caused the app to have the same name across versions. As a result, macOS automatically removed the old files during installation. Currently, the stable version is fine because its name is correct, but the nightly and beta versions are mislabeled. After my fix, users will need to uninstall the old nightly and beta versions and reinstall them for everything to work properly.

**Comment by gabrielle-ong** [comment]
I see, thanks @hiento09 for explaining and resolving! Marking as Complete - issue is fixed after reinstalling nightly.
