### ISSUE TITLE
bug: Duplicate BOS Token in Hugging Face Chat Templates

### ISSUE THREAD

**Issue by Van-QA** [janhq/cortex.cpp#618]
**Description:**
When using chat templates in Hugging Face, the Beginning-OfSentence (BOS) token is often already included in the template. However, Llama.cpp also automatically adds the BOS token, resulting in a duplicate BOS token. 

**Expected behavior:**
The system should automatically detect and remove any duplicate BOS tokens in the chat template. This would ensure proper functioning of the chat system without causing errors due to redundant tokens.

**Additional context:**
This issue may cause unexpected behavior or errors in the chat system. It is recommended that Cortex checks for and deduplicates the BOS token if it is present in the user's template to maintain a consistent and error-free chat experience.

**Comment by dan-menlo** [comment]
@nguyenhoangthuan99 I am putting this as a sub-issue of #1151. This issue may be stale if HF has fixed upstream

**Comment by nguyenhoangthuan99** [comment]
**Problem**
This is example of huggingface chat template that we are using `<|begin_of_text|><|start_header_id|>system<|end_header_id|>\n\n{system_message}<|eot_id|><|start_header_id|>user<|end_header_id|>\n\n{prompt}<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n`

The token `<|begin_of_text|>` is BOS token. However, when we use this chat template, the llama.cpp engine automatically add `<|begin_of_text|>` to the prompt -> there are 2 BOS token in the prompt e.g. `<|begin_of_text|><|begin_of_text|><|start_header_id|>system<|end_header_id|>\n\n{system_message}<|eot_id|>`. 

This issue won't affect too much to the response, and most models still work well with this. We are using cortex with double BOS token with llama.cpp engine without any error. 

**Solution**
There are 2 solutions right now for this:
- Handle at cortex.llamacpp engine. Every time, when run inference we need to check if there is BOS token of that model in the chat template. the BOS token is parsed from GGUF file by llama.cpp
- Handle at cortex.cpp side. We need to save BOS token to model.yml and let cortex.cpp remove it when request to cortex.llamacpp engine.

I think the first solution is better because we don't need to update the cortex.cpp part and model.yml file which is related to many other parts of cortex.cpp. 

This issue is not critical, and it needs effort to read llama.cpp source to handle.

**Comment by nguyenhoangthuan99** [comment]
I want to close this issue because llama.cpp set `tokenizer_add_bos` default to false on this [PR](https://github.com/ggerganov/llama.cpp/pull/7530/files#diff-150dc86746a90bad4fc2c3334aeb9b5887b3adad3cc1459446717638605348efR2315) 
![Image](https://github.com/user-attachments/assets/0f9e6da3-ddaf-4b6f-b06f-4e75ffd941c9)

For that reason, this bug no longer appear when running inference with llama.cpp.
Tested with cortex.cpp, when running inference, no warning log about duplicated BOS token appeared.
![Image](https://github.com/user-attachments/assets/5533431d-1b02-4d91-9b0e-1c00db46264c)

**Comment by gabrielle-ong** [comment]
Solved by llama.cpp upstream (thanks @nguyenhoangthuan99 for investigating)
